version: "3"

services:

  shopware:
    image: dockware/dev:6.5.0.0
    container_name: tecsafe-sw6-plugin-shopware
    ports:
      - "8080:80"
      - "3306:3306"
      - "22:22"
      - "7888:8888"
      - "7999:9999"
      - "7998:9998"
    networks:
      - web
      #- ddev_default
    environment:
      - XDEBUG_ENABLED=1
    volumes:
      - ".:/var/www/html/custom/plugins/MadTecsafe"
      - ".env.local:/var/www/html/.env.local"
      - "db_volume:/var/lib/mysql"
    extra_hosts:
      - "tecsafe-headless-shop.ddev.site:192.168.192.9"

volumes:
  db_volume:
    driver: local

networks:
  web:
    external: false
  ddev_default:
    external: true
