name: Build

on:
  pull_request:
  push:
  release:

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install shopware-cli
        uses: FriendsOfShopware/shopware-cli-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build plugin
        run: |
          mkdir -p build/zip build/release
          shopware-cli extension zip --release --output-directory ./build/zip .
          unzip build/zip/*.zip -d build/release/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/release/*
          prerelease: true

      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: plugin-zip
      #    path: build/*.zip
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
